[project]
name = "agent-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "langgraph>=1.1.10",
    "loguru>=0.7.3",
    "microsandbox>=0.4.5",
    "openai>=2.36.0",
    "pandas>=3.0.2",
    "pillow>=12.2.0",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "tabulate>=0.10.0",
]

[project.optional-dependencies]
dev = [
    "httpx>=0.28.1",
    "mypy>=2.0.0",
    "pandas-stubs>=3.0.0.260204",
    "pytest>=9.0.3",
    "ruff>=0.15.12",
    "typing-extensions>=4.15.0",
]

[tool.mypy]
plugins = "pydantic.mypy"
python_version = "3.12"
check_untyped_defs = true
disallow_any_explicit = true
disallow_untyped_calls = true
disallow_untyped_defs = true
no_implicit_optional = true
show_error_context = true
show_column_numbers = true
warn_redundant_casts = true
ignore_missing_imports = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D1",       # undocumented
    "D213",     # multi-line summary second line
    "ERA001",   # ignore detection of commented-out code
    "TD001",    # invalid todo tag
    "TD002",    # missing todo author
    "TD003",    # missing todo link
    "T201",     # allow use of print statement
    "I001",     # import block is un-sorted or un-formatted
    "INP001",   # file does not exist
    "S101",     # use of assert statement
    "ANN101",   # missing type annotation for self in method
    "ANN102",   # missing type annotation for cls in classmethod
    "PLR0913",  # too many arguments in function definition
    "PLR2004",  # magic value used in comparison
    "RUF001",   # allow unicode string normalization issues
    "RUF003",   # allow ambiguous unicode character usage
]
unfixable = [
    "F841", # unused variable
]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["src"]

[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__"]
reportMissingImports = false
reportMissingTypeStubs = false
